Repository rozukke/lace, pull requests merged in 2024-09, with the labels that each got.

#5 Add code emission
  README.md
  flake.nix
  src/air.rs
  src/lexer/cursor.rs
  src/lexer/mod.rs
  src/lib.rs
  src/main.rs
  src/parser.rs
  src/runtime.rs
  src/symbol.rs
Labels: enhancement

#6 Fix negative immediate values emitting wrong
  src/air.rs
Labels: bug

#8 Allow directives without a label
  src/parser.rs
Labels: invalid

#9 Refactor errors
  src/air.rs
  src/error.rs
  src/lexer/cursor.rs
  src/lexer/mod.rs
  src/lib.rs
  src/main.rs
  src/parser.rs
  src/symbol.rs
Labels: enhancement

#15 Fix various error message bugs
  src/error.rs
  src/lexer/mod.rs
  src/main.rs
  src/parser.rs
Labels: fix

#16 Add runtime
  Cargo.lock
  Cargo.toml
  src/air.rs
  src/lexer/mod.rs
  src/lib.rs
  src/main.rs
  src/parser.rs
  src/runtime.rs
  src/symbol.rs
  tests/files/hw.asm
  tests/integration_tests.rs
Labels: enhancement

#17 Add traps and usability fixes
  README.md
  src/lexer/mod.rs
  src/main.rs
  src/parser.rs
  src/runtime.rs
  src/symbol.rs
Labels: enhancement, fix

#18 Add logo to README.md
  README.md
  logo.png
Labels: documentation, enhancement

#19 Remove indexmap dependency
  Cargo.lock
  Cargo.toml
  src/symbol.rs
Labels: enhancement, invalid

#20 Add file watching
  Cargo.lock
  Cargo.toml
  src/error.rs
  src/lib.rs
  src/main.rs
  src/parser.rs
  src/symbol.rs
  tests/files/hw.asm
Labels: enhancement

#22 Fix not emitting and several runtime bugs
  Cargo.lock
  Cargo.toml
  README.md
  src/air.rs
  src/error.rs
  src/lib.rs
  src/main.rs
  src/runtime.rs
Labels: enhancement, fix

#31 Fix labels that look like hex erroring
  src/lexer/mod.rs
Labels: behaviour, fix

#32 Fix memory being reclaimed too early
  src/main.rs
  src/symbol.rs
Labels: bug, fix

#34 Add negative hex literals
  src/lexer/mod.rs
  src/parser.rs
Labels: enhancement, behaviour

#33 Fix incorrect range check for PC offset values
  src/air.rs
Labels: bug, behaviour

#36 Fix running and compiling
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/runtime.rs
  tests/integration_tests.rs
Labels: documentation, enhancement, fix

#37 Make file watching consistent across editors
  src/main.rs
Labels: behaviour, fix

#40 Make watcher delay and check for files
  src/main.rs
Labels: behaviour

#45 Implement `PUTSP` trap
  src/runtime.rs
Labels: feature
